import { Profile } from './user';

export interface Team {
  id: string;
  hackathon_id: string;
  name: string;
  description: string;
  required_skills: string[];      // skills the team is still looking for
  current_member_ids: string[];
  max_members: number;
  owner_id: string;
  is_open: boolean;               // false once team is full or owner closes it
  created_at?: string;
}

export interface TeamWithMembers extends Team {
  members: Profile[];
}

// Result of the AutoMatch algorithm — one suggested teammate
export interface TeammateMatch {
  profile: Profile;
  match_score: number;            // 0–100
  match_reasons: string[];        // human-readable reasons shown in the UI
}

// Result of the JoinTeam recommendation — one suggested team
export interface TeamMatch {
  team: Team;
  match_score: number;            // 0–100
  match_reasons: string[];
}

// A single message in the team workspace chat
export interface ChatMessage {
  id: string;
  team_id: string;
  sender_id: string;
  sender_name: string;
  content: string;
  is_ai_message: boolean;         // true for AI Mentor responses
  created_at: string;
}

// A task generated by AI or created manually
export interface Task {
  id: string;
  team_id: string;
  title: string;
  description: string;
  assigned_to_id: string;
  assigned_to_name: string;
  status: 'todo' | 'in-progress' | 'done';
  created_at?: string;
}

// A roadmap phase generated by AI for a specific hackathon duration
export interface RoadmapPhase {
  phase_number: number;
  time_range: string;             // e.g. "Hour 1–2"
  title: string;
  tasks: string[];
}
